//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nalarium {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nalarium.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already defined..
        /// </summary>
        internal static string Activation_TypeAlreadyExists {
            get {
                return ResourceManager.GetString("Activation_TypeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid base64 data..
        /// </summary>
        internal static string Base64_InvalidData {
            get {
                return ResourceManager.GetString("Base64_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeParserId is required when parsers are used..
        /// </summary>
        internal static string CodeParser_CodeParserIdRequired {
            get {
                return ResourceManager.GetString("CodeParser_CodeParserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required in the application configuration file..
        /// </summary>
        internal static string Config_SettingRequired {
            get {
                return ResourceManager.GetString("Config_SettingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Day_Friday {
            get {
                return ResourceManager.GetString("Day_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Day_Monday {
            get {
                return ResourceManager.GetString("Day_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Day_Saturday {
            get {
                return ResourceManager.GetString("Day_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Day_Sunday {
            get {
                return ResourceManager.GetString("Day_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thurdsay.
        /// </summary>
        internal static string Day_Thursday {
            get {
                return ResourceManager.GetString("Day_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Day_Tuesday {
            get {
                return ResourceManager.GetString("Day_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Day_Wednesday {
            get {
                return ResourceManager.GetString("Day_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colons (&quot;:&quot;) are not allowed in Value names or scopes..
        /// </summary>
        internal static string General_ColonNotAllowed {
            get {
                return ResourceManager.GetString("General_ColonNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing element &apos;{0}&apos;.
        /// </summary>
        internal static string General_MissingElement {
            get {
                return ResourceManager.GetString("General_MissingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string Month_April {
            get {
                return ResourceManager.GetString("Month_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string Month_August {
            get {
                return ResourceManager.GetString("Month_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string Month_December {
            get {
                return ResourceManager.GetString("Month_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string Month_February {
            get {
                return ResourceManager.GetString("Month_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string Month_January {
            get {
                return ResourceManager.GetString("Month_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string Month_July {
            get {
                return ResourceManager.GetString("Month_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string Month_June {
            get {
                return ResourceManager.GetString("Month_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string Month_March {
            get {
                return ResourceManager.GetString("Month_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Month_May {
            get {
                return ResourceManager.GetString("Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string Month_November {
            get {
                return ResourceManager.GetString("Month_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string Month_October {
            get {
                return ResourceManager.GetString("Month_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string Month_September {
            get {
                return ResourceManager.GetString("Month_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr.
        /// </summary>
        internal static string Name_Dr {
            get {
                return ResourceManager.GetString("Name_Dr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string Name_I {
            get {
                return ResourceManager.GetString("Name_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to II.
        /// </summary>
        internal static string Name_II {
            get {
                return ResourceManager.GetString("Name_II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to III.
        /// </summary>
        internal static string Name_III {
            get {
                return ResourceManager.GetString("Name_III", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jr.
        /// </summary>
        internal static string Name_Jr {
            get {
                return ResourceManager.GetString("Name_Jr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string Name_Mr {
            get {
                return ResourceManager.GetString("Name_Mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mrs.
        /// </summary>
        internal static string Name_Mrs {
            get {
                return ResourceManager.GetString("Name_Mrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms.
        /// </summary>
        internal static string Name_Ms {
            get {
                return ResourceManager.GetString("Name_Ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sr.
        /// </summary>
        internal static string Name_Sr {
            get {
                return ResourceManager.GetString("Name_Sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportCreator is required for adding data..
        /// </summary>
        internal static string Report_CreatorRequired {
            get {
                return ResourceManager.GetString("Report_CreatorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporter is not initialized..
        /// </summary>
        internal static string Report_NotInitialized {
            get {
                return ResourceManager.GetString("Report_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not set on reporter..
        /// </summary>
        internal static string Report_NotSet {
            get {
                return ResourceManager.GetString("Report_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured report {0} is not valid..
        /// </summary>
        internal static string Report_NotValid {
            get {
                return ResourceManager.GetString("Report_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one text delimiter is required..
        /// </summary>
        internal static string Text_DelimiterRequired {
            get {
                return ResourceManager.GetString("Text_DelimiterRequired", resourceCulture);
            }
        }
    }
}
